
---

- name: Setup Jenkins on CI/CD node
  hosts: ci_node
  become: true
  roles:
    - jenkins

- name: Setup observability tools on obs-server
  hosts: obs_node
  become: true
  roles:
    - metrics
    - opensearch