
---

- name: Stage I - App Server
  hosts: app_node
  become: true
  roles:
    - docker
    - node-exporter
    - application-server

- name: Stage I - Observability Server
  hosts: obs_node
  become: true
  roles:
    - docker
    - node-exporter


- name: Stage I - CI/CD Server
  hosts: ci_node
  become: true
  roles:
    - docker
    - node-exporter
    - vault